# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubGrid.ui'
#
# Created: Wed Sep 05 16:50:20 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SubGrid(object):
    def setupUi(self, SubGrid):
        SubGrid.setObjectName(_fromUtf8("SubGrid"))
        SubGrid.resize(536, 522)
        SubGrid.setSizeIncrement(QtCore.QSize(0, 0))
        SubGrid.setStyleSheet(_fromUtf8("/* Common style */\n"
"* { font: 75 10pt \"Miriam Transparent\"; }\n"
"\n"
"/* QSpinBoxes style */\n"
"QSpinBox {\n"
"    margin : 2px;\n"
"    /*border : 10px;*/\n"
"    padding : 10px;\n"
"}"))
        self.gridLayout_2 = QtGui.QGridLayout(SubGrid)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.square_A2 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_A2.sizePolicy().hasHeightForWidth())
        self.square_A2.setSizePolicy(sizePolicy)
        self.square_A2.setAlignment(QtCore.Qt.AlignCenter)
        self.square_A2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_A2.setMinimum(0)
        self.square_A2.setMaximum(9)
        self.square_A2.setProperty("value", 2)
        self.square_A2.setObjectName(_fromUtf8("square_A2"))
        self.gridLayout.addWidget(self.square_A2, 0, 1, 1, 1)
        self.square_C1 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_C1.sizePolicy().hasHeightForWidth())
        self.square_C1.setSizePolicy(sizePolicy)
        self.square_C1.setAlignment(QtCore.Qt.AlignCenter)
        self.square_C1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_C1.setMinimum(0)
        self.square_C1.setMaximum(9)
        self.square_C1.setProperty("value", 7)
        self.square_C1.setObjectName(_fromUtf8("square_C1"))
        self.gridLayout.addWidget(self.square_C1, 2, 0, 1, 1)
        self.square_C2 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_C2.sizePolicy().hasHeightForWidth())
        self.square_C2.setSizePolicy(sizePolicy)
        self.square_C2.setAlignment(QtCore.Qt.AlignCenter)
        self.square_C2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_C2.setMinimum(0)
        self.square_C2.setMaximum(9)
        self.square_C2.setProperty("value", 8)
        self.square_C2.setObjectName(_fromUtf8("square_C2"))
        self.gridLayout.addWidget(self.square_C2, 2, 1, 1, 1)
        self.square_C3 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_C3.sizePolicy().hasHeightForWidth())
        self.square_C3.setSizePolicy(sizePolicy)
        self.square_C3.setAlignment(QtCore.Qt.AlignCenter)
        self.square_C3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_C3.setSpecialValueText(_fromUtf8(""))
        self.square_C3.setMinimum(0)
        self.square_C3.setMaximum(9)
        self.square_C3.setProperty("value", 9)
        self.square_C3.setObjectName(_fromUtf8("square_C3"))
        self.gridLayout.addWidget(self.square_C3, 2, 2, 1, 1)
        self.square_B3 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_B3.sizePolicy().hasHeightForWidth())
        self.square_B3.setSizePolicy(sizePolicy)
        self.square_B3.setAlignment(QtCore.Qt.AlignCenter)
        self.square_B3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_B3.setMinimum(0)
        self.square_B3.setMaximum(9)
        self.square_B3.setProperty("value", 9)
        self.square_B3.setObjectName(_fromUtf8("square_B3"))
        self.gridLayout.addWidget(self.square_B3, 1, 2, 1, 1)
        self.square_A1 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_A1.sizePolicy().hasHeightForWidth())
        self.square_A1.setSizePolicy(sizePolicy)
        self.square_A1.setAlignment(QtCore.Qt.AlignCenter)
        self.square_A1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_A1.setMinimum(0)
        self.square_A1.setMaximum(9)
        self.square_A1.setProperty("value", 1)
        self.square_A1.setObjectName(_fromUtf8("square_A1"))
        self.gridLayout.addWidget(self.square_A1, 0, 0, 1, 1)
        self.square_B2 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_B2.sizePolicy().hasHeightForWidth())
        self.square_B2.setSizePolicy(sizePolicy)
        self.square_B2.setAlignment(QtCore.Qt.AlignCenter)
        self.square_B2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_B2.setMinimum(0)
        self.square_B2.setMaximum(9)
        self.square_B2.setProperty("value", 5)
        self.square_B2.setObjectName(_fromUtf8("square_B2"))
        self.gridLayout.addWidget(self.square_B2, 1, 1, 1, 1)
        self.square_B1 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_B1.sizePolicy().hasHeightForWidth())
        self.square_B1.setSizePolicy(sizePolicy)
        self.square_B1.setAlignment(QtCore.Qt.AlignCenter)
        self.square_B1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_B1.setMinimum(0)
        self.square_B1.setMaximum(9)
        self.square_B1.setProperty("value", 4)
        self.square_B1.setObjectName(_fromUtf8("square_B1"))
        self.gridLayout.addWidget(self.square_B1, 1, 0, 1, 1)
        self.square_A3 = QtGui.QSpinBox(SubGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_A3.sizePolicy().hasHeightForWidth())
        self.square_A3.setSizePolicy(sizePolicy)
        self.square_A3.setSizeIncrement(QtCore.QSize(0, 0))
        self.square_A3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.square_A3.setAutoFillBackground(False)
        self.square_A3.setAlignment(QtCore.Qt.AlignCenter)
        self.square_A3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.square_A3.setMinimum(0)
        self.square_A3.setMaximum(9)
        self.square_A3.setProperty("value", 3)
        self.square_A3.setObjectName(_fromUtf8("square_A3"))
        self.gridLayout.addWidget(self.square_A3, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(SubGrid)
        QtCore.QMetaObject.connectSlotsByName(SubGrid)

    def retranslateUi(self, SubGrid):
        SubGrid.setWindowTitle(QtGui.QApplication.translate("SubGrid", "Form", None, QtGui.QApplication.UnicodeUTF8))

